/* Generated by: JavaCC 21 Parser Generator. Do not edit.
 * Generated Code for ListNBT AST Node type
 * by the ASTNode.java.ftl template
 */
package cn.nukkit.nbt.snbt.ast;

import cn.nukkit.nbt.snbt.BaseNode;


public class ListNBT extends BaseNode {
}


