/* Generated by: JavaCC 21 Parser Generator. Do not edit.
 * Generated Code for Value AST Node type
 * by the ASTNode.java.ftl template
 */
package cn.nukkit.nbt.snbt.ast;

import cn.nukkit.nbt.snbt.BaseNode;


public class Value extends BaseNode {
}


