package cn.nukkit.block.state.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum MinecraftCardinalDirection {
    EAST,

    NORTH,

    SOUTH,

    WEST
}
