package cn.nukkit.block.state.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType2 {
    MOSSY_COBBLESTONE,

    PRISMARINE_BRICK,

    PRISMARINE_DARK,

    PRISMARINE_ROUGH,

    PURPUR,

    RED_NETHER_BRICK,

    RED_SANDSTONE,

    SMOOTH_SANDSTONE
}
