package cn.nukkit.block.state.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType4 {
    CUT_RED_SANDSTONE,

    CUT_SANDSTONE,

    MOSSY_STONE_BRICK,

    SMOOTH_QUARTZ,

    STONE
}
