package cn.nukkit.utils.random;

import io.netty.util.internal.ThreadLocalRandom;

public interface RandomSource {
    static RandomSource create() {
        return create(RandomSupport.generateUniqueSeed());
    }

    static RandomSource create(long seed) {
        return new NukkitRandomSource(seed);
    }

    /**
     * Create a new RandomSource using the random long generated by {@link #nextLong()}
     */
    RandomSource fork();

    void setSeed(long seed);

    /**
     * Generate random integer between {@link Integer#MIN_VALUE} and {@link Integer#MIN_VALUE}
     */
    int nextInt();

    /**
     * Generate random integer between 0 and bound - 1
     */
    int nextInt(int bound);

    default int nextIntBetweenInclusive(int min, int max) {
        return this.nextInt(max - min + 1) + min;
    }

    long nextLong();

    boolean nextBoolean();

    float nextFloat();

    /**
     * Next double 0-1
     */
    double nextDouble();

    double nextGaussian();

    default void consumeCount(int count) {
        for (int i = 0; i < count; ++i) {
            this.nextInt();
        }
    }

    /**
     * Generate a random int in the range min-max,include min and max
     */
    default int nextInt(int min, int max) {
        if (min >= max) {
            throw new IllegalArgumentException("bound - origin is non positive");
        } else {
            return min + this.nextInt(max + 1 - min);
        }
    }
}
