package cn.nukkit.newblockstate.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Damage {
    BROKEN,

    SLIGHTLY_DAMAGED,

    UNDAMAGED,

    VERY_DAMAGED
}
