package cn.nukkit.newblockstate.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum LeverDirection {
    DOWN_EAST_WEST,

    DOWN_NORTH_SOUTH,

    EAST,

    NORTH,

    SOUTH,

    UP_EAST_WEST,

    UP_NORTH_SOUTH,

    WEST
}
