package cn.nukkit.newblockstate.property.enums;

/**
 * @author daoge_cmd <br>
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum NewLogType {
    ACACIA,

    DARK_OAK
}
