package cn.nukkit.newblockstate.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum SaplingType {
    ACACIA,

    BIRCH,

    DARK_OAK,

    JUNGLE,

    OAK,

    SPRUCE
}
