package cn.nukkit.newblockstate.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum TurtleEggCount {
    FOUR_EGG,

    ONE_EGG,

    THREE_EGG,

    TWO_EGG
}
