package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum ChemistryTableType {
    COMPOUND_CREATOR,

    MATERIAL_REDUCER,

    ELEMENT_CONSTRUCTOR,

    LAB_TABLE
}
