package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Color {
    BLACK,

    BLUE,

    BROWN,

    CYAN,

    GRAY,

    GREEN,

    LIGHT_BLUE,

    LIME,

    MAGENTA,

    ORANGE,

    PINK,

    PURPLE,

    RED,

    SILVER,

    WHITE,

    YELLOW
}
