package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Damage {
    UNDAMAGED,
    SLIGHTLY_DAMAGED,
    BROKEN,
    VERY_DAMAGED;

    public Damage next(){
        return values()[this.ordinal()+1];
    }
}
