package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum DoublePlantType {
    SUNFLOWER,
    SYRINGA,
    GRASS,
    FERN,
    ROSE,
    PAEONIA
}
