package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum FlowerType {
    POPPY,
    ORCHID,
    ALLIUM,
    HOUSTONIA,
    TULIP_RED,
    TULIP_ORANGE,
    TULIP_WHITE,
    TULIP_PINK,
    OXEYE,
    CORNFLOWER,
    LILY_OF_THE_VALLEY,
}
