package cn.nukkit.block.property.enums;

import cn.nukkit.math.BlockFace;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum LeverDirection {
    DOWN_EAST_WEST(0, "down_x", BlockFace.DOWN),

    DOWN_NORTH_SOUTH(7, "down_z", BlockFace.DOWN),

    EAST(1, "east", BlockFace.EAST),

    NORTH(4, "north", BlockFace.NORTH),

    SOUTH(3, "south", BlockFace.SOUTH),

    UP_EAST_WEST(6, "up_x", BlockFace.UP),

    UP_NORTH_SOUTH(5, "up_z", BlockFace.UP),

    WEST(2, "west", BlockFace.WEST);


    private static final LeverDirection[] META_LOOKUP = new LeverDirection[values().length];
    private final int meta;
    private final String name;
    private final BlockFace facing;

    LeverDirection(int meta, String name, BlockFace face) {
        this.meta = meta;
        this.name = name;
        this.facing = face;
    }

    public int getMetadata() {
        return this.meta;
    }

    public BlockFace getFacing() {
        return this.facing;
    }

    @Override
    public String toString() {
        return this.name;
    }

    public static LeverDirection byMetadata(int meta) {
        if (meta < 0 || meta >= META_LOOKUP.length) {
            meta = 0;
        }
        return META_LOOKUP[meta];
    }

    public static LeverDirection forFacings(BlockFace clickedSide, BlockFace playerDirection) {
        return switch (clickedSide) {
            case DOWN -> switch (playerDirection.getAxis()) {
                case X -> DOWN_EAST_WEST;
                case Z -> DOWN_NORTH_SOUTH;
                default ->
                        throw new IllegalArgumentException("Invalid entityFacing " + playerDirection + " for facing " + clickedSide);
            };
            case UP -> switch (playerDirection.getAxis()) {
                case X -> UP_EAST_WEST;
                case Z -> UP_NORTH_SOUTH;
                default ->
                        throw new IllegalArgumentException("Invalid entityFacing " + playerDirection + " for facing " + clickedSide);
            };
            case NORTH -> NORTH;
            case SOUTH -> SOUTH;
            case WEST -> WEST;
            case EAST -> EAST;
        };
    }

    public String getName() {
        return this.name;
    }

    static {
        for (LeverDirection face : values()) {
            META_LOOKUP[face.getMetadata()] = face;
        }
    }
}
