package cn.nukkit.block.property.enums;

import cn.nukkit.api.Internal;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 *
 * Placeholder，use {@link cn.nukkit.math.BlockFace}
 * @author daoge_cmd
 */
@Internal
public enum MinecraftBlockFace {
}
