package cn.nukkit.block.property.enums;

import org.jetbrains.annotations.ApiStatus;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 *
 * Placeholder，use {@link cn.nukkit.math.BlockFace}
 * @author daoge_cmd
 */
@ApiStatus.Internal
public enum MinecraftBlockFace {
}
