package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum MonsterEggStoneType {
    CHISELED_STONE_BRICK,

    COBBLESTONE,

    CRACKED_STONE_BRICK,

    MOSSY_STONE_BRICK,

    STONE,

    STONE_BRICK
}
