package cn.nukkit.block.property.enums;

/**
 * @author daoge_cmd <br>
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum OldLogType {
    OAK,

    SPRUCE,

    BIRCH,

    JUNGLE
}
