package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Orientation {
    DOWN_EAST,

    DOWN_NORTH,

    DOWN_SOUTH,

    DOWN_WEST,

    EAST_UP,

    NORTH_UP,

    SOUTH_UP,

    UP_EAST,

    UP_NORTH,

    UP_SOUTH,

    UP_WEST,

    WEST_UP
}
