package cn.nukkit.block.property.enums;

import cn.nukkit.math.BlockFace;

import java.util.Arrays;

import static cn.nukkit.math.BlockFace.*;
/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum Orientation {
    DOWN_EAST(DOWN, EAST),

    DOWN_NORTH(DOWN, NORTH),

    DOWN_SOUTH(DOWN, SOUTH),

    DOWN_WEST(DOWN, WEST),

    EAST_UP(EAST, UP),

    NORTH_UP(NORTH, UP),

    SOUTH_UP(SOUTH, UP),

    UP_EAST(UP, EAST),

    UP_NORTH(UP, NORTH),

    UP_SOUTH(UP, SOUTH),

    UP_WEST(UP, WEST),

    WEST_UP(WEST, UP);

    BlockFace first;
    BlockFace second;

    Orientation(BlockFace first, BlockFace second) {
        this.first = first;
        this.second = second;
    }

    public static final Orientation[] VALUES = values();

    public static Orientation getByFaces(BlockFace first, BlockFace second) {
        return Arrays.stream(VALUES).filter(o -> o.first == first && o.second == second).findFirst().orElse(null);
    }
}
