package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * Placeholder，use {@link cn.nukkit.math.BlockFace.Axis}
 * @author daoge_cmd
 */
@Deprecated
public enum PillarAxis {}
