package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType4 {
    MOSSY_STONE_BRICK,
    SMOOTH_QUARTZ,
    STONE,
    CUT_SANDSTONE,
    CUT_RED_SANDSTONE
}
