package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType {
    BRICK,

    COBBLESTONE,

    NETHER_BRICK,

    QUARTZ,

    SANDSTONE,

    SMOOTH_STONE,

    STONE_BRICK,

    WOOD
}
