package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType3 {
    END_STONE_BRICK,
    SMOOTH_RED_SANDSTONE,
    POLISHED_ANDESITE,
    ANDESITE,
    DIORITE,
    POLISHED_DIORITE,
    GRANITE,
    POLISHED_GRANITE
}
