package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneType {
    ANDESITE,

    ANDESITE_SMOOTH,

    DIORITE,

    DIORITE_SMOOTH,

    GRANITE,

    GRANITE_SMOOTH,

    STONE
}
