package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum StoneSlabType {
    SMOOTH_STONE,
    SANDSTONE,
    WOOD,
    COBBLESTONE,
    BRICK,
    STONE_BRICK,
    QUARTZ,
    NETHER_BRICK,
}
