package cn.nukkit.block.property.enums;

import cn.nukkit.math.BlockFace;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.NotNull;

import javax.annotation.Nullable;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
@RequiredArgsConstructor
public enum TorchFacingDirection {
    UNKNOWN(BlockFace.UP),
    WEST(BlockFace.EAST),
    EAST(BlockFace.WEST),
    NORTH(BlockFace.SOUTH),
    SOUTH(BlockFace.NORTH),
    TOP(BlockFace.UP);

    private final BlockFace torchDirection;

    /**
     * The direction that the flame is pointing.
     */
    public BlockFace getTorchDirection() {
        return torchDirection;
    }

    public @Nullable static TorchFacingDirection getByTorchDirection(@NotNull BlockFace face) {
        return switch (face) {
            default -> null;
            case UP -> TOP;
            case EAST -> WEST;
            case WEST -> EAST;
            case SOUTH -> NORTH;
            case NORTH -> SOUTH;
        };
    }

    /**
     * The direction that is touching the attached block.
     */
    @NotNull public BlockFace getAttachedFace() {
        return switch (this) {
            default -> BlockFace.DOWN;
            case EAST -> BlockFace.EAST;
            case WEST -> BlockFace.WEST;
            case SOUTH -> BlockFace.SOUTH;
            case NORTH -> BlockFace.NORTH;
        };
    }

    public @Nullable static TorchFacingDirection getByAttachedFace(@NotNull BlockFace face) {
        return switch (face) {
            default -> null;
            case DOWN -> TorchFacingDirection.TOP;
            case SOUTH -> TorchFacingDirection.SOUTH;
            case NORTH -> TorchFacingDirection.NORTH;
            case EAST -> TorchFacingDirection.EAST;
            case WEST -> TorchFacingDirection.WEST;
        };
    }
}
