package cn.nukkit.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum WallBlockType {
    ANDESITE,

    BRICK,

    COBBLESTONE,

    DIORITE,

    END_BRICK,

    GRANITE,

    MOSSY_COBBLESTONE,

    MOSSY_STONE_BRICK,

    NETHER_BRICK,

    PRISMARINE,

    RED_NETHER_BRICK,

    RED_SANDSTONE,

    SANDSTONE,

    STONE_BRICK
}
