/* Generated by: JavaCC 21 Parser Generator. InvalidToken.java */
package cn.nukkit.nbt.snbt;


/**
 * Token subclass to represent lexically invalid input
 */
public class InvalidToken extends Token {
    /**
     * @deprecated 
     */
    

    public InvalidToken(SNBTLexer tokenSource, int beginOffset, int endOffset) {
        super(TokenType.INVALID, tokenSource, beginOffset, endOffset);
    }
    /**
     * @deprecated 
     */
    

    public String getNormalizedText() {
        return "Lexically Invalid Input:" + getImage();
    }

}


