package org.powernukkitx.block.property.enums;

import org.powernukkitx.math.BlockFace;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum MinecraftCardinalDirection {
    SOUTH,
    WEST,
    NORTH,
    EAST;

    public final static MinecraftCardinalDirection[] VALUES = values();

    public static MinecraftCardinalDirection fromBlockFace(BlockFace face) {
        return switch (face) {
            case SOUTH -> SOUTH;
            case WEST -> WEST;
            case NORTH -> NORTH;
            case EAST -> EAST;
            default -> throw new IllegalArgumentException();
        };
    }
}
