package org.powernukkitx.block.property.enums;

import org.jetbrains.annotations.ApiStatus;
import org.powernukkitx.math.BlockFace;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * Placeholder，use {@link BlockFace.Axis}
 * @author daoge_cmd
 */
@ApiStatus.Internal
public enum PillarAxis {}
