name: Build & Deploy Javadoc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Javadoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x gradlew

      - name: Build Javadoc
        run: ./gradlew javadoc

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: build/docs/javadoc

      - uses: actions/deploy-pages@v5
